# Experiment 3: PYTHON DATA ANALYSIS (PANDAS)

### Negranza, Jake Andrei D.

### 2ECE-A

### September 15, 2026

In [3]:
import pandas as pd

#Load the csv file
cars = pd.read_csv('cars.csv')

## A. Positional and Label-based Slicing

In [8]:
# Part a
print("Shape of DataFrame: ", cars.shape)
print("Column Names: ", cars.columns.tolist())

# Part b
cars_6_to_10 = cars.iloc[5:10]

# Part c
cars_6_to_10[['Model', 'mpg', 'cyl', 'hp', 'gear']]

Shape of DataFrame:  (32, 12)
Column Names:  ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

## B. Model Lookup

In [11]:
# part a
toyota = cars[cars['Model'] == 'Toyota Corolla']
display(toyota)

# part b
pontiac = cars[cars['Model'] == 'Pontiac Firebird'][['Model', 'mpg', 'hp', 'wt',]]
display(pontiac)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

## C. Multi-model Subsetting

In [16]:
selected_models = ['Datsun 710', 'Lotus Europa', 'Ferrari Dino']
selected_cars = cars[cars['Model'].isin(selected_models)][['Model' ,'mpg', 'cyl', 'hp', 'gear']]

display(selected_cars)
print("Shape of selected_cars", selected_cars.shape)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Shape of selected_cars (3, 5)